// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtG0uwk8ykGLlyVAMrC-QdHZRgiqYzJgY',
    appId: '1:239405644229:web:eec99cd3b6ee1de834f3ac',
    messagingSenderId: '239405644229',
    projectId: 'unilink-3fef4',
    authDomain: 'unilink-3fef4.firebaseapp.com',
    databaseURL: 'https://unilink-3fef4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unilink-3fef4.appspot.com',
    measurementId: 'G-Q2X4PREMH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBruxjFLSlhxkzSotL9jGI1TZK_0C8wmZw',
    appId: '1:239405644229:android:7d9a91208f57e23c34f3ac',
    messagingSenderId: '239405644229',
    projectId: 'unilink-3fef4',
    databaseURL: 'https://unilink-3fef4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unilink-3fef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgj3Cr0jhmQG4NJFkXMq4UEqXchitx_rQ',
    appId: '1:239405644229:ios:c8c0615183eef6ee34f3ac',
    messagingSenderId: '239405644229',
    projectId: 'unilink-3fef4',
    databaseURL: 'https://unilink-3fef4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unilink-3fef4.appspot.com',
    iosBundleId: 'com.example.unilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtG0uwk8ykGLlyVAMrC-QdHZRgiqYzJgY',
    appId: '1:239405644229:web:502d1ad2de222b3a34f3ac',
    messagingSenderId: '239405644229',
    projectId: 'unilink-3fef4',
    authDomain: 'unilink-3fef4.firebaseapp.com',
    databaseURL: 'https://unilink-3fef4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unilink-3fef4.appspot.com',
    measurementId: 'G-5FNB756KZ0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_IE88r1epOcp3HL-zlG-p4QNtLimgOw',
    appId: '1:884733483668:ios:d72e915a591a76f3bd3281',
    messagingSenderId: '884733483668',
    projectId: 'licenta-425311',
    databaseURL: 'https://licenta-425311-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'licenta-425311.appspot.com',
    iosBundleId: 'com.example.unilink',
  );

}