// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP4B_WUj_nvwXNHNGKUKSMZVC3YD6rtxI',
    appId: '1:884733483668:web:2df902c30980c90dbd3281',
    messagingSenderId: '884733483668',
    projectId: 'licenta-425311',
    authDomain: 'licenta-425311.firebaseapp.com',
    storageBucket: 'licenta-425311.appspot.com',
    measurementId: 'G-R5HFRF7CNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk7Uk4dMk5UeIfFXY9kk9nJyD_pDHKrOI',
    appId: '1:884733483668:android:248f87d8fefd94ebbd3281',
    messagingSenderId: '884733483668',
    projectId: 'licenta-425311',
    storageBucket: 'licenta-425311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_IE88r1epOcp3HL-zlG-p4QNtLimgOw',
    appId: '1:884733483668:ios:d72e915a591a76f3bd3281',
    messagingSenderId: '884733483668',
    projectId: 'licenta-425311',
    storageBucket: 'licenta-425311.appspot.com',
    iosBundleId: 'com.example.unilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP4B_WUj_nvwXNHNGKUKSMZVC3YD6rtxI',
    appId: '1:884733483668:web:386353e225109ad6bd3281',
    messagingSenderId: '884733483668',
    projectId: 'licenta-425311',
    authDomain: 'licenta-425311.firebaseapp.com',
    storageBucket: 'licenta-425311.appspot.com',
    measurementId: 'G-HBL3EWG0Y7',
  );
}
